### ISSUE TITLE
python read_grasps_from_file.py --gripper robotiq_85问题

### ISSUE THREAD

**Issue by xiaofeiso** [Hymwgk/simulate_dataset_generation#2]
大佬，我运行python read_grasps_from_file.py --gripper robotiq_85查看自己的点云模型生成的抓取文件，出现这个问题，好像说sdf文件有问题，但是看起来和YCB数据集的没有什么不同，该怎么改呢？
Traceback (most recent call last):
  File "read_grasps_from_file.py", line 229, in <module>
    grasps_with_score, obj, ply_name, obj_name = open_npy_and_obj(npy_names[0])
  File "read_grasps_from_file.py", line 52, in open_npy_and_obj
    obj_ = GraspableObject3D(sdf, mesh)
  File "/mnt/f/code/PointNetGPD/dex-net/src/dexnet/grasping/graspable_object.py", line 117, in __init__
    raise ValueError('Must initialize 3D graspable object with 3D sdf')
ValueError: Must initialize 3D graspable object with 3D sdf

**Comment by xiaofeiso** [comment]
我又重新跑了，利用simulate_dataset_generation的采样代码而不是python generate-dataset-canny.py，最后成功读取了，只不过不知道是不是因为自己的模型比较小，而且是自制的，
我把
    m_good = m[m[:, -2] <= 0.4]
    m_good = m_good[np.random.choice(len(m_good), size=25, replace=True)]

    m_bad = m[m[:, -2] >= 1.8]
    m_bad = m_bad[np.random.choice(len(m_bad), size=25, replace=True)]
改成
    m_good = m[m[:, -2] <= 2.5]

    m_good = m_good[np.random.choice(len(m_good), size=25, replace=True)]

    m_bad = m[m[:, -2] > 2.5]
    m_bad = m_bad[np.random.choice(len(m_bad), size=25, replace=True)]
才能够显示抓取，是不是因为齿轮这一类的零件小，所以抓取分数也不够高。
