### ISSUE TITLE
table_pc.npy问题

### ISSUE THREAD

**Issue by xiaofeiso** [Hymwgk/simulate_dataset_generation#3]
table_pc.npy是桌子的点云文件吗？ 我看到get_legal_grasps_with_score.py里面需要这个文件，是不是需要用bg_table.stl文件转换，还有我没有看到有关pc.npy生成的代码，只看到raw_pc.npy的生成。

**Comment by xiaofeiso** [comment]
大佬，你有没有你的桌子和挡板的文件，能不能分享一下。

**Comment by Hymwgk** [comment]
不好意思已经找不到了，这个项目我已经很长时间不接着做了  所以有很多也记不起来了

**Comment by xiaofeiso** [comment]
没事，我自己画了一个桌子和挡板，只不过不知道是不是零件太小了，还是相机位置设置的不对，python  show_raw_pc.py  --gripper  panda  --show  5后可以看到桌子，看不到桌子上的零件。

**Comment by xiaofeiso** [comment]
大佬，我想问下运行./blender  -P /mnt/f/code/simulate_dataset_generation/raw_pc_generate.py出现下面有一个AttributeError: 'Object' object has no attribute 'scan_type'的问题，这个是不是blensor或者bpy模块没安装成功的原因。

Scene 000 has 4 meshes 
Process Process-1:
Traceback (most recent call last):
  File "/home/xiaofeisong/blensor/2.79/python/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/xiaofeisong/blensor/2.79/python/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/f/code/simulate_dataset_generation/raw_pc_generate.py", line 96, in do_job
    scanner.scan_type = "kinect"
AttributeError: 'Object' object has no attribute 'scan_type'

**Comment by xiaofeiso** [comment]
我修改kinect相机的位置，但是python show_raw_pc.py --gripper panda --show 5显示的桌子只有桌面和两个桌腿，零件也看不见，和大佬你的结果不一样。
